### ISSUE TITLE
Running into error with CUDA on Windows

### ISSUE THREAD

**Issue by ChuckinAllen** [ashawkey/stable-dreamfusion#236]
### Description

Cuda Error when trying to run.

### Steps to Reproduce
running installation process 

No CUDA runtime is found, using CUDA_HOME= <Default Installation File>

### Expected Behavior

When trying to run it gives me an error no cuda runtime found, I am running on windows using git-bash to run programs even though I go to the file that cuda is installed in it's not picking it up for some reason.

### Environment

Windows 10 using git-bash, running a 3080 as a gpu.

**Comment by marsilainen** [comment]
PyTorch needs to be using gpu.  You can configure the correct install at https://pytorch.org.  For CUDA, v11.7 should work.

**Comment by ChuckinAllen** [comment]
I believe that is the issue, Trying to resolve it's giving me the _grid_encoder error I should be able to figure the rest out did not see the versions until you pointed it out thank you.

**Comment by ChuckinAllen** [comment]
Yep that did it I uninstalled CUDA 12.1 and installed CUDA 11.7 resolved the issue was able to install _grid_encoder after that issue was resolved.
